### ISSUE TITLE
feat(guide): create Health and Emergency Info page

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-tahiti#169]
The design is available on [figma](https://www.figma.com/file/VtzXViXjXah3IuWn2xBRae/Website?node-id=736%3A51).

![Health and Emergency Info](https://user-images.githubusercontent.com/33367546/157028725-ff04d612-f877-4095-a51d-4272aac1c540.png)

**Comment by ORKO06** [comment]
I would like to work on this.
