### ISSUE TITLE
feat(guide): create Archive page

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-tahiti#170]
The design is available on [figma](https://www.figma.com/file/VtzXViXjXah3IuWn2xBRae/Website?node-id=736%3A51).

![Archive Page](https://user-images.githubusercontent.com/33367546/157028846-32b6679f-b56b-4a62-a51a-1a5b307fa761.png)

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue.
