### ISSUE TITLE
bug: footer links not formatted properly

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-tahiti#180]
**Describe the bug**
Footer links are not formatted correctly.

**To Reproduce**
Check footer at [project-tahiti-staging](https://project-tahiti-staging.herokuapp.com) landing page.

**Screenshots**
![image](https://user-images.githubusercontent.com/33367546/161848184-fd33cd11-e77e-4721-9a20-4a88507b9bde.png)

**Comment by ORKO06** [comment]
@rutajdash 
What changes need to be done here?

**Comment by rutajdash** [comment]
UPDATE: Shift to React v18 fixes the issue
