### ISSUE TITLE
bug: small card image not fitting properly

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-tahiti#181]
**Describe the bug**
In mobile view, the image of the small article card is not filling its container.

**Screenshots**
![image](https://user-images.githubusercontent.com/33367546/161849069-674786a1-81f2-40d4-90f4-db3578a28349.png)

**Comment by subha-asish** [comment]
i want to work on this

**Comment by ORKO06** [comment]
I would like to work on this

**Comment by ORKO06** [comment]
Which type of the above would be preferred?

Type 1:- 
![image](https://user-images.githubusercontent.com/74568847/168823553-1682faa4-6a6c-4bf5-99cc-38f89ef566c7.png)

Type 2:-
![image](https://user-images.githubusercontent.com/74568847/168823633-bea8442d-d9b3-49f8-8719-39548b0cfad4.png)

The difference between both is object-fit: cover;

**Comment by 120EE0692** [comment]
> Which type of the above would be preferred?
> 
> Type 1:- ![image](https://user-images.githubusercontent.com/74568847/168823553-1682faa4-6a6c-4bf5-99cc-38f89ef566c7.png)
> 
> Type 2:- ![image](https://user-images.githubusercontent.com/74568847/168823841-c29f0b5d-9b44-4507-aefb-31d14cda3489.png)
> 
> The difference between both is object-fit: cover;
@ORKO06 in type 2 are the images are a bit blur?

**Comment by ORKO06** [comment]
> > @ORKO06 in type 2 are the images are a bit blur?

Yes as the image width is getting shrunk to maintain the height of the image also in 1st the image is getting cropped for around 15% on both the sides in horizontal direction

**Comment by rutajdash** [comment]
@ORKO06 confirming, type 1 is what we did in the end right?

**Comment by 120EE0692** [comment]
> @ORKO06 confirming, type 1 is what we did in the end right?

YES
