### ISSUE TITLE
bug: footer text

### ISSUE THREAD

**Issue by ORKO06** [Monday-Morning/project-tahiti#217]
**Describe the bug**
In the footer, it is written 2015-2020 whereas it will be 2022

**To Reproduce**
change the text from 2020 to 2022

**Screenshots**
![image](https://user-images.githubusercontent.com/74568847/172179910-c6819c1a-08a6-406f-9510-69c7251ab407.png)

**Comment by sambit-sankalp** [comment]
Hey @ORKO06,
Thank you for detecting the bug. This issue is already solved in the repository. We will bring it to production in our next release.
