### ISSUE TITLE
bug: cursor is not pointer in back to campus button

### ISSUE THREAD

**Issue by ORKO06** [Monday-Morning/project-tahiti#262]
**Describe the bug**

**To Reproduce**

1. Go to 'https://mondaymorning.nitrkl.ac.in/campus/studentActivities'
2. Hover on 'Back To Campus'

**Expected behavior**
The cursor should be pointer

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue.
