### ISSUE TITLE
docs: add nextjs in readme

### ISSUE THREAD

**Issue by 120EE0692** [Monday-Morning/project-tahiti#270]
We are using nextJs in our project.
Add nextJs with its official website link, in the built with section of readme.

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by rutajdash** [comment]
@Shurtu-gal would you like to take up this issue?

**Comment by Shurtu-gal** [comment]
Sure👍
