### ISSUE TITLE
[Admin]refactor: change the author cards

### ISSUE THREAD

**Issue by sambit-sankalp** [Monday-Morning/project-tahiti#276]
**Current Scenario**
Currently, the author card has a select input. Refactor  it to a search functionality(Refer to the previous version of Admin Panel[Posts/Add New])

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/82284130/195282023-c4e85d24-14f5-4f23-bc22-5db062f9a744.png)
UI should be similar to this.

**Additional context**
It is similar to the search and pick functionality.

**Comment by Anish-Sarawgi** [comment]
Can I work on this issue.?
