### ISSUE TITLE
feat: add go to archives section in footer

### ISSUE THREAD

**Issue by 120EE0692** [Monday-Morning/project-tahiti#307]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/83752052/201409745-6da6af81-aedb-4efe-8e91-7b992e9f8947.png">

link to [figma](https://www.figma.com/file/VtzXViXjXah3IuWn2xBRae/Website?node-id=736%3A51)

**Comment by Shurtu-gal** [comment]
Can I work on this?
