### ISSUE TITLE
feat: add error catch in all render methods

### ISSUE THREAD

**Issue by rutajdash** [Monday-Morning/project-tahiti#314]
**Is your feature request related to a problem? Please describe.**
Yes, the getStaticProps and getServerProps code is not error handles and results in server crashes.

**Describe the solution you'd like**
Add a try/catch error handler in all Nextjs render methods
- getStaticPaths
- getStaticProps
- getServerSideProps

For an error case, the error should be passed in the props instead and should be handled in the page.

**Comment by rutajdash** [comment]
@Shurtu-gal would you like to take up this issue?

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal would you like to take up this issue?

Yes👍

**Comment by Shurtu-gal** [comment]
Can you please clarify what do you mean by handling of error by page?

**Comment by rutajdash** [comment]
> Can you please clarify what do you mean by handling of error by page?

Sure.
All the base pages (found in the `pages` folder) have the above-mentioned methods used to pre-render or server-side render the data for the page which is then passed as props to the layout. Those methods do not have a try/catch block hence all errors cause a fatal crash even if it is not actually a fatal crash.
Hence, we need to add a try/catch block and pass the caught error along with any data already retrieved as props to the main function.

**Comment by Shurtu-gal** [comment]
> > Can you please clarify what do you mean by handling of error by page?
> 
> Sure. All the base pages (found in the `pages` folder) have the above-mentioned methods used to pre-render or server-side render the data for the page which is then passed as props to the layout. Those methods do not have a try/catch block hence all errors cause a fatal crash even if it is not actually a fatal crash. Hence, we need to add a try/catch block and pass the caught error along with any data already retrieved as props to the main function.

And how will it be handled in the main function?

**Comment by rutajdash** [comment]
> > > Can you please clarify what do you mean by handling of error by page?
> > 
> > 
> > Sure. All the base pages (found in the `pages` folder) have the above-mentioned methods used to pre-render or server-side render the data for the page which is then passed as props to the layout. Those methods do not have a try/catch block hence all errors cause a fatal crash even if it is not actually a fatal crash. Hence, we need to add a try/catch block and pass the caught error along with any data already retrieved as props to the main function.
> 
> And how will it be handled in the main function?

For now, we can display a standard 500 error page which already exists. However future scope would require us to add error boundaries and allow the display of partial data.

**Comment by Shurtu-gal** [comment]
Okay! Thanks.

**Comment by rutajdash** [comment]
The 500 page would be added as a condition in the same way the loading animation is shown now.
