### ISSUE TITLE
style: reduce the size of icon in 404 and 500 page

### ISSUE THREAD

**Issue by 120EE0692** [Monday-Morning/project-tahiti#323]
The size of the icon in 404 and 500 page is not as per the design, due to which the message is not visible to the user, when such pages are encountered in the desktop. 

Current 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83752052/204080675-90f6d14a-0f19-4126-84b7-5d07c09a67ca.png">

Required 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/83752052/204080699-a1b26120-a87a-46b0-8023-21936e1746d4.png">

**Comment by AdityaAB4** [comment]
I want to fix this issue

**Comment by 120EE0692** [comment]
> 

@AdityaAB4 thankyou for showing your interest to resolve this issue. But this issue is already assigned. Kindly check some other issues.

Happy Hacking.
