### ISSUE TITLE
feat(subcategory): add departments routes in subcategory page 

### ISSUE THREAD

**Issue by 120EE0692** [Monday-Morning/project-tahiti#326]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/83752052/204114365-463a608a-77e7-462e-bae1-75b35deba813.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/83752052/204114378-bf25c0a7-0b56-477a-a125-10d0732ec359.png">

on clicking these buttons it should navigate to /campus/[department_name}/1
Routes must be defined in getRoutes.js file.

**Comment by Shurtu-gal** [comment]
Can I work on this?
