### ISSUE TITLE
feat: add app recommender components

### ISSUE THREAD

**Issue by 120EE0692** [Monday-Morning/project-tahiti#397]
No design was prepared in figma.
An image is attached below for for inspiration purpose
![798c56cc-6a02-419e-82af-51622bf30230](https://user-images.githubusercontent.com/83752052/211157910-978d69e5-e703-4d61-898f-52278e29a4cb.jpg)

Make sure the font and color you used should match with website theme.

**Comment by Shurtu-gal** [comment]
Should it be displayed only in mobiles and tablets?

**Comment by 120EE0692** [comment]
> Should it be displayed only in mobiles and tablets?

Only mobile
