### ISSUE TITLE
feat(theme): create dark theme for the website

### ISSUE THREAD

**Issue by 120EE0692** [Monday-Morning/project-tahiti#413]
@Monday-Morning/team-2022-23 

- You have to plan and execute the entire task yourself.
- break the issue in multiple sub issues.
- create all sub issues in github and assign yourself.

**Comment by rutajdash** [comment]
@120EE0692 please make an umbrella issue [(like this)](https://github.com/flutter/flutter/issues/91605) for this and track all related issues in it.
